"""empty message

Revision ID: 71e47f0c60e3
Revises: 78817124f4e9
Create Date: 2018-03-28 07:44:15.431203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e47f0c60e3'
down_revision = '78817124f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_redirect_log_code', table_name='redirect_log')
    op.create_index(op.f('ix_redirect_log_code'), 'redirect_log', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirect_log_code'), table_name='redirect_log')
    op.create_index('ix_redirect_log_code', 'redirect_log', ['code'], unique=False)
    # ### end Alembic commands ###
