"""empty message

Revision ID: 8b37ae6a38ab
Revises: 78817124f4e9
Create Date: 2018-05-09 19:37:02.497119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b37ae6a38ab'
down_revision = '78817124f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_redirect_list_code', table_name='redirect_list')
    op.create_index(op.f('ix_redirect_list_code'), 'redirect_list', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirect_list_code'), table_name='redirect_list')
    op.create_index('ix_redirect_list_code', 'redirect_list', ['code'], unique=False)
    # ### end Alembic commands ###
